resources:
  # Build info of first build to bundle
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: myArtifactory
      buildName: svc_build
      buildNumber: 1

pipelines:
  - name: createReleaseBundlePipeline
    steps:
      - name: createReleaseBundleStep
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: myReleaseBundle
          releaseBundleVersion: "${run_number}"
          dryRun: false
          inputResources:
            - name: myBuildInfo
          outputResources:
            - name: myReleaseBundle
