resources:
  # Build info of first build to bundle
  - name: gosvc_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: myArt
      buildName: app_dev_pipeline_su204
      buildNumber: 1

  # Build info of second build to bundle
 # - name: appl_promoted_build_info1
 #   type: BuildInfo
#    configuration:
#      sourceArtifactory: demoArt
#      buildName: backend_build
#      buildNumber: 1

  # Release bundle
  - name: release_bundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: myDist
      name: demo_rb
      version: v1.0.0

  # Signed version of the same release bundle
  - name: signed_bundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: myDist
      name: demo_rb
      version: v1.0.0

pipelines:
  - name: demo_release_mgmt
    steps:
      - name: bundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: demo_rb
          releaseBundleVersion: v1.0.${run_number}
          dryRun: false
          sign: true
          description: "some random test description"
          inputResources:
            - name: gosvc_promoted_build_info
              trigger: true
          outputResources:
            - name: release_bundle
         
      - name: sign
        type: SignReleaseBundle
        configuration:
          inputResources:
            - name: release_bundle
          outputResources:
            - name: signed_bundle
