pipelines:
  - name: bash_step_example
    - name: build
      type: Bash
      configuration:
        nodePool: my_node_pool
        environmentVariables:
          env1: value1
          env2:
            default: value2
            description: Example Variable
            values:
              - value2
              - value3
            allowCustom: false
        runtime:
          type: image
          image:
            auto:
              language: nodejs
              versions:
                - "10.16.3"
        inputResources:
          - name: src
      execution:
        onExecute:
          - cd $res_src_resourcePath
          - npm install
          - mkdir -p testresults && mkdir -p codecoverage
          - $res_src_resourcePath/node_modules/.bin/mocha --recursive "tests/**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=testresults/testresults.xml
          - $res_src_resourcePath/node_modules/.bin/istanbul --include-all-sources cover -root "routes" node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "tests/**/*.spec.js"
          - $res_src_resourcePath/node_modules/.bin/istanbul report cobertura --dir codecoverage
          - save_tests $res_src_resourcePath/testresults/testresults.xml
        onSuccess:
          - send_notification mySlack "build completed"
